### ISSUE TITLE
request: auto constructor for simple namedtuple use-case

### ISSUE THREAD

**Issue by jeremyschulman** [maximkulkin/lollipop#40]
Let's say a common use-case is the constructor class is from a namedtuple.  Presently, a user would need to do the following:

````python
Person = namedtuple('Person', ['name', 'age'])

PersonType = Object({
    'name': String(validate=Length(min=1)),
   'age': Integer()
}, constructor=Person)
````

The user is required to create a duplicate mapping of name fields in both `Person` and `PersonType`, in this case `name` and `age`.  

Would it be conceivably useful to have do something like the following, and the lollipop library meta-creates the actual namedtuple type instance when an instance of the PersonType is created.  Thus the sequence:

````python

PersonType = Object({
    'name': String(validate=Length(min=1)),
    'age': Integer()
}, constructor='Person')       # lollipop see's a string vs. a class, knowns to do the magic

me = PersonType.loads(dict(name='jeremy', age=40))

me.name
# 'jeremy'

me.age
# 40
````

**Comment by jeremyschulman** [comment]
I realize that if I omit the `constructor` parameter, the resulting Object type from instance construction is a `dict`.  But the use-case for a namedtuple is rather nice (in general) for real-only use cases.  For example, let's say we want to define a schema for input parameters; and as an instance of input parameters are passed to a calling function (as a namedtuple class) we ensure the user does not mistakenly change (write) over the params.

**Comment by maximkulkin** [comment]
@jeremyschulman You can use something like [OpenStruct](https://github.com/hamidnazari/python-ostruct) as constructor:

```python
import lollipop.types as lt
import lollipop.validators as lv
from ostruct import OpenStruct

PERSON = lt.Object({
    'name': lt.String(validate=lv.Length(min=1)),
    'age': lt.Integer(),
}, constructor=OpenStruct)

me = PERSON.load({'name': 'jeremy', 'age': 40})
print me
# => {'name': 'jeremy', 'age': 40}
print me.name
# => jeremy
print me.age
# => 40
```
I'm not making this part of library

**Comment by jeremyschulman** [comment]
@maximkulkin - very cool, I will check out ostruct library!

I was toying around with an approach like this:

```python
def type_maker(cls_name, lt_cls, **kwargs):
    return type(
        cls_name,
        (namedtuple(cls_name, lt_cls.fields.keys()),),
        {'dump': lambda self: lt_cls.dump(self)}
    )(**kwargs)


SystemFactsType = lt.Object(
    {
        'vendor': lt.String(),
        'os_name': lt.String(),
        'os_version': lt.String(),
        'mgmt_ipaddr': lt.String(),
        'mgmt_ifname': lt.String(),
        'serial_number': lt.String(),
        'hw_model': lt.String()
    },
    constructor=lambda **k: type_maker('SystemFacts', SystemFactsType, **k)
)
````
