### ISSUE TITLE
Feature request: support for specifying type for dict keys

### ISSUE THREAD

**Issue by Ragsboss** [maximkulkin/lollipop#43]
The current type Dict allows specifying types only for values, but we have a need to specify one type for all keys too..

**Comment by maximkulkin** [comment]
The idea was that Dict represent schema for data, that will be used in "wire" format to serialize basic types to be transferred over the wire (e.g. JSON), in that case keys can be only strings. What is your use case?
Am I correct that you want to specify a type for all keys in a Dict and that type will be used in both serialization and deserialization?

**Comment by Ragsboss** [comment]
In my case keys are strings but they need to be valid ip addresses, so I'd like to use a validated_type

**Comment by maximkulkin** [comment]
Added support for Dict key types in master.

@Ragsboss Can you check it out and if everything looks fine I will issue release.

**Comment by Ragsboss** [comment]
@maximkulkin awesome. This is exactly what I needed. Thank you. I'll await the release.

**Comment by maximkulkin** [comment]
@Ragsboss v1.1 is out
