### ISSUE TITLE
Asymmetry in load/dump for Dict with key_type and dict as values_type

### ISSUE THREAD

**Issue by python-app-generation** [maximkulkin/lollipop#54]
I think there is a problem with the Dict type when using both key_type verification and a values_type dictionary:

In Dict.dump, the key is used in its original / non-dumped form to lookup the value type. However, in Dict.load, the dumped key is used to lookup the value type.

This works fine when using native types as key type such as String and Integer since they map to the same loaded/dumped value. But it's causing a problem when using a more complex key type (e.g. in my case an Enum that dumps to a string).

I believe, in Dict.load, key_type.load should be called **before** the lookup of the value type, so that the lookup is again performed with the original / non-dumped value.

**Comment by maximkulkin** [comment]
So, correct me if I'm wrong. You have a dictionary mapping your enum types to some values. You dump them and get a dictionary mapping strings (enum representations) to something that represent your dumped values. Now you're saying that to do reverse transformation (load), your data already has enum values as keys (although your dumped key are strings). If so, you're wrong: load() and dump() operations are reverse of each other ( load(dump(x)) == x  and  dump(load(y)) == y ).

**Comment by python-app-generation** [comment]
To avoid confusion with the Enum type, I try to demonstrate the Dict problem with a simpler example:

```
class IntegerString(Integer):
    """Integer type that dumps to / loads from a string."""

    def dump(self, value):
        return str(value)

    def load(self, data):
        return int(data)


intdict = Dict(key_type=IntegerString(), value_types={1: String(), 2: String()})

dumped = intdict.dump({1: 'First', 2: 'Second'})
print(dumped)   # {'1': 'First', '2': 'Second'}
# The dump works as expected: key and values are dumped correctly.

loaded = intdict.load(dumped)
print(loaded)   # {}
# Oops, the values are lost. This is because the lookup of the value_types is
# done with the dumped keys '1' and '2', instead of the original keys 1 and 2.
```

The solution that works for me:

```
class Dict(Type):

    def load(self, data, *args, **kwargs):
        if data is MISSING or data is None:
            self._fail('required')

        if not is_mapping(data):
            self._fail('invalid')

        errors_builder = ValidationErrorBuilder()
        result = {}
        for k, v in iteritems(data):
            # First, load the key to its original type.
            try:
                k = self.key_type.load(k, *args, **kwargs)
            except ValidationError as ve:
                errors_builder.add_error(k, ve.messages)

            # Now, lookup the value type.
            value_type = self.value_types.get(k)
            if value_type is None:
                continue

            try:
                result[k] = value_type.load(v, *args, **kwargs)
            except ValidationError as ve:
                errors_builder.add_error(k, ve.messages)

        errors_builder.raise_errors()

        return result
        
```

**Comment by maximkulkin** [comment]
Ok, now I get it. Although still you're using it in kind of wrong way. Obviously, your values always have the same type (String()), so it would be better to declare your type like this:
```python
intdict = Dict(key_type=IntegerString(), value_types=String())
```

With this setup you won't hit this problem and that is the use case for which support for key types was added. The use case when your dictionary can have keys of different types is mostly for, well, serializing data represented by a fixed structure dictionaries (and thus keys are strings).

But no worries, I will fix that for consistency.

**Comment by python-app-generation** [comment]
Thank you. This was a simplified example. My real use case has different value types.
